### ISSUE TITLE
Seems like a bug

### ISSUE THREAD

**Issue by Eekain** [AhmadAlkholy/Javascript-Chess-Game#1]
I'm not good at chess.

I arrived at the setup of (rows: letters,from A; columns: numbers, from 1):
A1: wKnight
A4: bKing
C7: wKnight
D1: bPawn
D4: bPawn
E4: wPawn
F5: wKing
F8: bBishop
G1: wPawn
G2: wBishop
H1: wRook
Black's Turn

Issue is: I cannot move D1 bPawn.
It's not the end of the game, and there is nothing blocking D1 from moving.
I am able to move the bBishop and the bKing.

Thanks for making this game!

**Comment by AhmadAlkholy** [comment]
Hello @Eekain 

I changed the entire code structure of the game and the issue is fixed.
Thank you for your comment.

**Comment by Eekain** [comment]
Thank you for doing so!
